### ISSUE TITLE
Suggestions re default values and optional option-arguments

### ISSUE THREAD

**Issue by mklement0** [trevorsenior/opt-md#10]
Currently, the default value in `### --default=SOMETHING, -d SOMETHING (default=foo)` is applied as follows:

If neither `--default` nor `-d` are specified,  `$('default')` and `$('d')` contain `foo`.

Ergo: not specifying the option _at all_ on the command line assigns the corresponding property the default value.

By contrast, specifying it _without an option-argument_, e.g., just `-d` instead of `-d bar`, actually assigns `true` to `$('default')` and `$('d')`, which is unexpected. Based on the syntax, given that the option-argument `SOMETHING` is _not_ marked as optional, I would expect parsing to fail, given that the required option-argument was not specified.

Complementarily, it would be great to be able to define _optional option-arguments_, such as with

    ### --default[=SOMETHING], -d[SOMETHING] (default=foo)

which would require slightly different logic:

* If neither `--default` nor `-d` are specified, leave `$('default')` and `$('d')` _undefined_.
* Apply the default value only if either `--default` or `-d` are specified _without option-argument_; e.g., just `-d`.
* Note that specifying a value for an optional option-argument inherently requires that the option and its value form a single token; e.g., `--default=bar` or `-dbar`.

A real-life example of such an option is `grep`'s  `--color[=WHEN]` option, which controls color-coding of the output; `WHEN` defaults to `never`, if only `--color` is specified.

**Comment by trevorsenior** [comment]
Hey @mklement0, 

Thanks for the feedback. This library could use some refreshing / it's been awhile since I've used it (I have been focusing on web applications vs. cli tools). I'll address this issue after work and throw the changes in `2.0.0` as it will be a breaking change for anyone who may be using the library.

**Comment by mklement0** [comment]
That sounds great, thanks.

If you feel inspired, here are some more suggestions (I have no sense of how difficult they'd be to implement):

You could also consider supporting inline styles, such as ``### `--default`[=*something*]``, which renders better both in HTML and in a man page (though still not optimally).

The ability to use unordered list items (`*`) in lieu of `###` to mark options would be great too.

Finally, moving to v2 may be an opportunity to (conceptually) rename the project to a more descriptive name.

**Comment by trevorsenior** [comment]
> Finally, moving to v2 may be an opportunity to (conceptually) rename the project to a more descriptive name.

Any suggestions welcome on that front.

**Comment by mklement0** [comment]
`opt-md`? (It's what the doctor ordered.)

**Comment by trevorsenior** [comment]
@mklement0 

I've spread the suggestions in this thread out into their own respective issues and will address them throughout this week.

- - -

`opt-md` is the new package name and it includes the fix for the main `-d` --> `true` issue. It will now throw an error if the types of the default value do not match what the input given is.

The `main` library has been deprecated on `npm`.

- - -

As a side note, the entire library has gone through a major cleanup:

* 100% ES6+ (babel)
* build system (gulp)
* Travis-CI testing

Hopefully this lowers the barrier for development on this project should you wish to poke around.

**Comment by mklement0** [comment]
That all sounds awesome - thank you.
